import { Driver } from "selenium-webdriver/chrome";
import { ableToSwitchToFrame } from "selenium-webdriver/lib/until";
import { Connor } from "./connorsPage";

const connor = new Connor ()

test("Sign in", async ()=> {
    await connor.navigate()
    await connor.MaxWindow()
    await connor.click(connor.SignBtn)
    await connor.driver.sleep(1000)
    await connor.click(connor.LibSelect)
    await connor.driver.sleep(1000)
    await connor.setInput(connor.LibSelect, "Springville Public Library")
    await connor.driver.sleep(1000)
    await connor.click(connor.SigninOp)
    await connor.driver.sleep(1500)
    await connor.click(connor.CardNum)
    await connor.driver.sleep(1000)
    await connor.setInput(connor.CardNum, "23451001004322")
    await connor.driver.sleep(1500)
    await connor.click(connor.Pin)
    await connor.driver.sleep(1000)
    await connor.setInput(connor.Pin, "8019")
    await connor.driver.sleep(1500)
    await connor.click(connor.SignBtn2)
    await connor.driver.sleep(1000)
})

test("Search for and check out a book", async ()=> {
    await connor.click(connor.Search)
    await connor.driver.sleep(1000)
    await connor.click(connor.SearchBox)
    await connor.driver.sleep(1000)
    await connor.setInput(connor.SearchBox, "Maze Runner")
    await connor.driver.sleep(1000)
    await connor.click(connor.ConfSearch)
    await connor.driver.sleep(1000)
    await connor.click(connor.BorrowBtn)
    await connor.driver.sleep(1000)
    await connor.click(connor.BorrowBtn2)
    await connor.driver.sleep(1000)
    await connor.click(connor.ClosePop)
    await connor.driver.sleep(1000)
})

test("Return book", async ()=> {
    await connor.click(connor.HomeBtn)
    await connor.driver.sleep(1000)
    await connor.click(connor.MyInvin)
    await connor.driver.sleep(1000)
    await connor.click(connor.ReturnBtn)
    await connor.driver.sleep(1000)
    await connor.click(connor.ReturnBtn2)
    await connor.driver.sleep(1000)
    await connor.click(connor.HomeBtn)
    await connor.driver.sleep(1000)
})

test("Add and remove from wish list", async ()=>{
    await connor.click(connor.Search)
    await connor.driver.sleep(1000)
    await connor.click(connor.SearchBox)
    await connor.driver.sleep(1000)
    await connor.setInput(connor.SearchBox, "Maze Runner")
    await connor.driver.sleep(1000)
    await connor.click(connor.ConfSearch)
    await connor.driver.sleep(1000)
    await connor.click(connor.AddtoWish)
    await connor.driver.sleep(1000)
    await connor.click(connor.MyInvin)
    await connor.driver.sleep(1000)
    await connor.click(connor.WishList)
    await connor.driver.sleep(1000)
    await connor.click(connor.RemoveWish)
    await connor.driver.sleep(1000)
    await connor.click(connor.RemoveWishConf)
    await connor.driver.sleep(1000)
    await connor.click(connor.HomeBtn)
    await connor.driver.sleep(1000)
})

test("Place and Remove a hold", async ()=> {
    await connor.click(connor.Search)
    await connor.driver.sleep(1000)
    await connor.click(connor.SearchBox)
    await connor.driver.sleep(1000)
    await connor.setInput(connor.SearchBox, "Crank Ellen Hopkins")
    await connor.driver.sleep(1000)
    await connor.click(connor.ConfSearch)
    await connor.driver.sleep(1000)
    await connor.click(connor.PlaceHold)
    await connor.driver.sleep(1000)
    await connor.click(connor.ClosePop)
    await connor.driver.sleep(1000)
    await connor.click(connor.MyInvin)
    await connor.driver.sleep(1000)
    await connor.click(connor.Holds)
    await connor.driver.sleep(1000)
    await connor.click(connor.RemoveHold)
    await connor.driver.sleep(1000)
    await connor.click(connor.RemoveHoldConf)
    await connor.driver.sleep(1000)
    await connor.click(connor.HomeBtn)
    await connor.driver.sleep(1000)
})

test("Sign out", async ()=> {
    await connor.click(connor.MyAccount)
    await connor.driver.sleep(1000)
    await connor.click(connor.SingOutBtn)
    await connor.driver.sleep(1000)
    await connor.driver.quit()
})